# Generated by Django 3.2.7 on 2021-09-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='e_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='g_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='s_sore',
            field=models.FloatField(default=0),
        ),
    ]
