# Generated by Django 3.2.7 on 2021-09-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210928_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='s_sore',
            new_name='s_score',
        ),
    ]
