# Generated by Django 3.2.7 on 2021-10-01 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_s_sore_user_s_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_score', models.FloatField(default=0)),
                ('s_score', models.FloatField(default=0)),
                ('g_score', models.FloatField(default=0)),
                ('first', models.IntegerField()),
                ('second', models.IntegerField()),
                ('third', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.RemoveField(
            model_name='user',
            name='e_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='g_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='s_score',
        ),
        migrations.AddField(
            model_name='mbti',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
