# Generated by Django 3.2.7 on 2021-10-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211001_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='first',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='second',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='third',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
