# Generated by Django 3.2.7 on 2021-09-20 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('E_rating', models.FloatField()),
                ('S_rating', models.FloatField()),
                ('G_rating', models.FloatField()),
                ('ESG_rating', models.FloatField()),
                ('scrap_cnt', models.IntegerField()),
                ('today_cnt', models.IntegerField()),
                ('scrap_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('publisher', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=10)),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporates.corporate')),
            ],
        ),
    ]
