# Generated by Django 3.2.7 on 2021-09-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0002_auto_20210923_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='woman_ratio',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
