# Generated by Django 3.2.7 on 2021-09-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0003_social_woman_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='governance',
            old_name='board_ration',
            new_name='board_ratio',
        ),
    ]
