# Generated by Django 3.2.7 on 2021-09-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0004_auto_20210927_1608'),
        ('corporates', '0004_rename_board_ration_governance_board_ratio'),
    ]

    operations = [
    ]
