# Generated by Django 3.2.7 on 2021-09-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0005_merge_20210928_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environment',
            old_name='news_cnt',
            new_name='news_neg_cnt',
        ),
        migrations.RenameField(
            model_name='governance',
            old_name='news_cnt',
            new_name='news_neg_cnt',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='news_cnt',
            new_name='news_neg_cnt',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='news_score',
        ),
        migrations.RemoveField(
            model_name='governance',
            name='news_score',
        ),
        migrations.RemoveField(
            model_name='social',
            name='news_score',
        ),
        migrations.AddField(
            model_name='environment',
            name='news_pos_cnt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='governance',
            name='news_pos_cnt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='news_pos_cnt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
