# Generated by Django 3.2.7 on 2021-10-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0007_auto_20210930_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='news',
            name='publisher',
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
