# Generated by Django 3.2.7 on 2021-10-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0009_news_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governance',
            name='board_independency',
            field=models.FloatField(),
        ),
    ]
