# Generated by Django 3.2.7 on 2021-10-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0010_alter_governance_board_independency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
